[platformio]
default_envs = esp32-s3

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
